### ISSUE TITLE
Port Range

### ISSUE THREAD

**Issue by sgutermann** [weareinteractive/ansible-ufw#11]
Maybe I am just missing it. But how would you define a port range?

ufw allow 1000:2000/tcp

**Comment by franklinkim** [comment]
Since this role is pretty much just a wrapper around ansible's ufw module, please see the [the module's documentation](http://docs.ansible.com/ansible/latest/ufw_module.html). Then sth like:

```yaml
# Allow port range 60000-61000
- ufw:
    rule: allow
    port: '60000:61000'
```

would translate to:

```yaml
ufw_rules:
    - { port: '60000:61000', rule: allow }
```
