### ISSUE TITLE
Make reset configurable?

### ISSUE THREAD

**Issue by pstoll** [weareinteractive/ansible-ufw#5]
I am using this role, thanks for making it.

Wanted to run a situation by you and get your thoughts and possibly ask for a feature. 

Question: How to let a host be in multiple roles, each of which configures its own set of ufw_rules? Today with the reset functionality, rules get clobbered if rules get re-executed because of the "reset" block in tasks/main.yml

Let's say I have 3 groups: load balancer, db, and app server. Each group has its own ufw_rules.

It all works if each group has its own server(s). But if a host is placed in multple groups, ufw setup does not work. This is because of the "reset" code in the main task.

I don't want to turn on 'hash_behaviour=merge' because that seems ...undesirable. See the gotcha section of this article: https://dantehranian.wordpress.com/2015/08/10/automating-linux-security-best-practices-with-ansible/  

I hacked the role locally to avoid doing the reset. Not ideal. Perhaps the first time through it could do a reset but subsequent executions could skip the reset. 

Any thoughts? 

Thanks,
 Perry

**Comment by franklinkim** [comment]
Hi Perry, 

must admit, haven't had this scenario yet but let's try to figure that out :)

Your right, setting the `hash_behaviour` is a absolute no go except for really small setups where you know nothing unexpected is gonna happen. The alternative is to use it within jinja templates for [hashes](http://docs.ansible.com/ansible/playbooks_filters.html#combining-hashes-dictionaries) or in this case arrays:

```Yaml
    ...
    ufw_rules_foo:
      - { from_ip: '127.0.0.1/8' }
      - { from_ip: '127.0.42.0/24', rule: deny }
    ufw_rules_bar:
      - { port: 80, rule: allow }
    ufw_rules: "{{ ufw_rules_foo + ufw_rules_bar}}"
    ...
```

One option would be to use multiple playbooks and run the role only for a specific tag:

```Yaml
- hosts: all
  roles:
    - {role: franklinkim.ufw, tags: ['ufw-reset']}
    ...

- hosts: db
  roles:
    - {role: franklinkim.ufw, tags: ['ufw-config']}
    ...
```
